name: 统一文档与任务管理
on:
  push:
    branches: [main]
    paths:
      - 'docs/**'
      - 'scripts/**'
  pull_request:
    branches: [main]
  workflow_dispatch:
  schedule:
    # 每天凌晨2点自动同步一次
    - cron: '0 2 * * *'

jobs:
  unified-docs-sync:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          
      - name: 设置Python环境
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          
      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: 统一文档任务管理
        run: |
          python scripts/unified-task-manager.py --mode=full-sync
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}