name: 同步文档任务到GitHub Issues
on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - 'scripts/**'
  workflow_dispatch:

jobs:
  sync-tasks:
    runs-on: ubuntu-latest
    steps:
    - name: 检出代码
      uses: actions/checkout@v5  # 更新这里

    - name: 设置Python环境
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
        # cache: 'pip'

    - name: 安装依赖
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # 推荐使用 requirements.txt
      # env:
      #   PIP_CACHE_DIR: /tmp/pip-cache

    - name: 解析文档任务
      run: |
        python scripts/parse_tasks.py
      env:
        PYTHONPATH: .

    - name: 创建GitHub Issues
      run: |
        python scripts/create_github_issues.py
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_REPOSITORY: ${{ github.repository }}

    - name: 上传任务JSON作为artifact
        uses: actions/upload-artifact@v4
        with:
          name: parsed-tasks
          path: tasks.json